version: '3'

services:
  db:
    container_name: db
    image: mysql:latest
    ports:
      - 3306:3306
    networks:
      - smart-city-network    
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - smart-city-volume:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  app:
    build: .
    ports:
      - 8000:8000
    devices:
      - /dev/video0:/dev/video0
    networks:
      - smart-city-network
    environment:
      DB_USERNAME: root
      DB_PASSWORD: ""
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: smart_city
      DB_SOCKET: ""
    restart: on-failure
networks:
  smart-city-network:
    name: smart-city-network
volumes:
  smart-city-volume:
